### ISSUE TITLE
Add cake-contrib user

### ISSUE THREAD

**Issue by pascalberger** [waxtell/Cake.Tools.ReadyAPI.TestRunner#3]
First of all, I wanted to thank you for adding to the Cake community by adding this addin.

We try to increasing the visibility of addins, and also trying to ensure their long term maintainability through the [Cake Contributions organization](https://cakebuild.net/community/cake-contrib) (see [blog post](http://cakebuild.net/blog/2016/08/cake-contribution-organization) for details)

To that end, we are asking addin creators to add the `cake-contrib` user on NuGet as a co-owner (this can be done through the NuGet website by clicking on Manage Owners on the package page).

Would you be interested in doing this? If you have any questions about this, please let me know. There was some initial concern that the Cake Team were trying to "take over" packages, and that couldn't be further from the truth, and if you have this concern, or others, I would like to address them.

If you're interested it would also be possible to move the repository to the [cake-contrib organization on GitHub](https://github.com/cake-contrib) where we can provide some build infrastructure and even more visibility to the addin.

Thanks!

**Comment by waxtell** [comment]
cake-contrib is now a co-owner!

**Comment by pascalberger** [comment]
Thanks for doing this 👍

**Comment by waxtell** [comment]
my pleasure!
